#                                                         Travaux pratiques sur K-means - Partie I


Dans la suite de ce document, les travaux porteront principalement sur l'agorithme de k-means. Le but de ces travaux est d'implémenter l'algorithme de k-means en python puis d'étudier des cas d'utilisation de l'algorithme. 



Importer les bibliothèques nécessaires. Cette cellule sera compélétée progressivement en fonction des besoins exprimés durant les travaux.

In [3]:
import random
import numpy as np



## Prise en main de numpy

Génerer une liste de 100 valeurs aléatoires.

In [4]:
liste_entiers = random.sample(range(100), 100)
print(liste_entiers)

[63, 97, 37, 55, 10, 95, 98, 34, 42, 75, 54, 1, 33, 21, 73, 78, 94, 40, 48, 64, 91, 76, 47, 60, 58, 32, 69, 87, 25, 41, 27, 61, 67, 86, 79, 28, 70, 89, 44, 23, 7, 20, 39, 5, 26, 22, 72, 71, 18, 2, 19, 46, 43, 93, 49, 88, 96, 92, 14, 62, 38, 85, 80, 45, 29, 53, 74, 31, 66, 52, 16, 59, 3, 81, 12, 68, 65, 51, 82, 0, 17, 4, 30, 99, 6, 15, 57, 13, 50, 11, 8, 35, 77, 24, 84, 36, 9, 83, 56, 90]


Créer un tableau, qu'on appelera tab, de type ndarray et de taille $10\times 10$.

In [5]:
tab = np.zeros((10, 10))
print(tab)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Créer une fonction avg qui calcule la moyenne d'un tableau ndarray de taille $n\times d$ donné en entrée, en résultat un tableau de taille $1\times d$ est fourni.

Exécuter la fonction avg sur tab. 

Créer une fonction, diff, qui calcule la différence entre un tableau ndarray de taille $n\times d$ appelé t1 et un tableau ndarray de taille $1\times d$ appelé t2, le résultat donné est un tableau ndarray de taille $n\times d$. A noter que la différence est opérée entre chaque ligne de t1 et l'unique ligne de t2.

Générer 10 valeurs aléatoires et transformer cette liste en tableau ndarray de taille $1\times 10$.
Puis exécuter diff sur tab et ce tableau nouvellement généré.

Créer une fonction, appelée l2, qui calcule la distance euclidienne entre deux points donnés en entrée. Ces points sont de taille $1\times d$. 

Créer une fonction, appelée l1, qui calcule la distance de Manhattan  entre deux points donnés en entrée. Ces points sont de taille $1\times d$. 

Créer une fonction, appelée frobenius_norm, qui reçoit un tableau ndarray de taille $n\times d$ et renvoie le résultat de l'opération suivante:

\begin{equation*}
\sqrt{ \sum_{i=1}^m \sum_{j=1}^d |a_{ij}|^2 }  
\end{equation*}

## Implémentation de k-means

Dans cette partie, nous allons implémenter l'agorithme de k-means.

Créer une fonction f0 qui choisit k (entier naturel positif) points au hasard à partir d'un jeu de données donné en entrée. L'entier k est aussi donné en entrée de la fonction f0.

Créer une fonction f1 qui calcule la distance entre chaque point d'un jeu de données donné en entrée et les k centroides donnés en entrée. La mesure de distance est aussi renseignée (par exemple euclidienne, manhattan...).
En sortie, une liste de clusters est attendue. Chaque cluster correspond à la liste d'indices de ses points.

Note: La distance euclidienne est le choix par défaut si l'utilisateur ne renseigne aucune mesure de distance. 

Créer la fonction f2 qui calcule les centroïdes des clusters nouvellement constitués.

Créer la fonction f3 qui vérifie s'il y a convergence de k-means. La fonction f3 doit proposer trois moyens de vérification de la convergence:
- les centroïdes de l'itération précédente sont les mêmes que ceux de l'iteration actuelle;
- la norme de Frobenius de la différence des valeurs des centroides de deux itérations consécutives ne dépasse pas un seuil donné en paramètre par l'utilisateur (par exemple 0.001)
- le seuil maximal d'itérations est dépassé (seuil renseigné par l'utilisateur). Ce choix est une option par défaut, la valeur par défaut est fixée à 30.

Créer la fonction, appelée run, qui exécute itérativement les trois fonctions f1, f2, f3 jusqu'à convergence. 
La fonction f0 est appelée une seule fois à la première itération.
Dans cette même fonction run, proposer la visualisation des centroides et les clusters associés. A chaque cluster on associe une couleur. 
La visualisation n'est lancée seulement si l'utilisateur le souhaite. 

# Application de k-means sur un jeu de données synthétique

Générer un jeu de données synthétique via la méthode make_blobs (https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_blobs.ht). Fixer le nombre de points (n_samples) à 2000 et le nombre de clusters (centers) à 4.

Appliquer k-means sur ce jeu de données avec $k=4$. Visualiser le résultat final.

Relancer k-means et visualiser les résultats de 10 premières itérations.

Relancer k-means en variant les différents choix de vérification de la convergence. Que constatez-vous?

Note: les centroides initiaux et la mesure de distance doivent être les mêmes pour chacun des choix.

Créer un autre jeu de données synthétique. Choisissez un nombre de clusters et un nombre de points que vous souhaitez. Puis lancer à nouveau k-means avec k égal au nombre de clusters choisi. 

Note: vous pourriez créer optionnellement  un jeu de données plus personnalisé en jouant sur les valeurs des paramètres centers, cluster_std et center_box.

## Application de k-means sur une image

Dans cette partie, nous allons effectuer une fragmentation de l'image "nature.jpg". Cela aboutira à plusieurs parties de forme variable représentant différents objects dans l'image.

Charger l'image nature.jpg avec la bibliothèque cv2. Puis afficher l'image.

Quelle est la taille de l'image? Stocker cette taille dans une variable appelée taille_originale.

Convertir l'image chargée à la taille $n\times 3$ avec $n$ le nombre de pixels et 3 le nombre de cannaux de couleurs. Puis afficher dans un graphe 3D l'image. 

Appliquer k-means sur l'image avec $k=3$. 

Note: si le temps d'exécution est relativement lent (dépassant 10 minutes), réduisez la taille de l'image avec la fonction resize proposée par la bibliothèque cv2 puis réexécuter les questions précédentes de cette partie.

Créer un tableau ndarray de taille $n\times 3$ contenant la valeur du centroide le plus proche de chaque point (pixel).

Convertir la taille de ce tableau à taille originale de l'image.  

Visualiser l'image originale et l'image obtenue via k-means. Qu'observez-vous?

Références:
- https://docs.anaconda.com/anaconda/install/windows/
- https://docs.python.org/3/library/random.html
- https://numpy.org/doc/stable/numpy-ref.pdf
- https://numpy.org/
- https://matplotlib.org/stable/tutorials/index.html
- https://docs.opencv.org/3.0-beta/modules/imgcodecs/doc/reading_and_writing_images.html 
- https://docs.opencv.org/3.0-beta/modules/imgproc/doc/geometric_transformations.html?highlight=resize#cv2.resize