#                                                         Travaux pratiques sur K-means - Partie I


Dans la suite de ce document, les travaux porteront principalement sur l'agorithme de k-means. Le but de ces travaux est d'implémenter l'algorithme de k-means en python puis d'étudier des cas d'utilisation de l'algorithme. 



Importer les bibliothèques nécessaires. Cette cellule sera compélétée progressivement en fonction des besoins exprimés durant les travaux.

In [3]:
import random
import numpy as np



## Prise en main de numpy

Génerer une liste de 100 valeurs aléatoires.

In [4]:
liste_entiers = random.sample(range(100), 100)
print(liste_entiers)

[80, 25, 26, 88, 65, 7, 5, 70, 73, 36, 51, 29, 99, 18, 20, 11, 42, 57, 40, 82, 92, 12, 49, 86, 94, 46, 85, 60, 15, 16, 84, 23, 45, 17, 34, 32, 48, 64, 1, 61, 89, 14, 78, 79, 27, 0, 22, 56, 30, 37, 68, 3, 67, 31, 93, 43, 2, 13, 8, 81, 66, 71, 98, 10, 39, 75, 74, 58, 53, 77, 87, 72, 54, 95, 28, 63, 41, 35, 33, 47, 6, 69, 97, 21, 90, 52, 76, 19, 4, 44, 24, 55, 38, 9, 50, 91, 83, 59, 62, 96]


Créer un tableau, qu'on appelera tab, de type ndarray et de taille $10\times 10$.

In [5]:
tab = np.zeros((10, 10))
print(tab)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Créer une fonction avg qui calcule la moyenne d'un tableau ndarray de taille $n\times d$ donné en entrée, en résultat un tableau de taille $1\times d$ est fourni.

In [6]:
def avg(ndarray):
    return np.mean(ndarray, axis=0)

Exécuter la fonction avg sur tab. 

In [7]:
result = avg(tab)
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Créer une fonction, diff, qui calcule la différence entre un tableau ndarray de taille $n\times d$ appelé t1 et un tableau ndarray de taille $1\times d$ appelé t2, le résultat donné est un tableau ndarray de taille $n\times d$. A noter que la différence est opérée entre chaque ligne de t1 et l'unique ligne de t2.

In [8]:
def diff(t1, t2):
    return t1 - t2

Générer 10 valeurs aléatoires et transformer cette liste en tableau ndarray de taille $1\times 10$.
Puis exécuter diff sur tab et ce tableau nouvellement généré.

In [17]:
t2 = np.random.rand(10)
resultat = diff(tab, t2)
print("Tab : ", tab)
print("T2 : ", t2)
print("Résultat : ", resultat)

Tab :  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
T2 :  [0.2188668  0.29429702 0.83695718 0.51244138 0.72919691 0.32470714
 0.76106692 0.37987903 0.22523713 0.8133488 ]
Résultat :  [[-0.2188668  -0.29429702 -0.83695718 -0.51244138 -0.72919691 -0.32470714
  -0.76106692 -0.37987903 -0.22523713 -0.8133488 ]
 [-0.2188668  -0.29429702 -0.83695718 -0.51244138 -0.72919691 -0.32470714
  -0.76106692 -0.37987903 -0.22523713 -0.8133488 ]
 [-0.2188668  -0.29429702 -0.83695718 -0.51244138 -0.72919691 -0.32470714
  -0.76106692 -0.37987903 -0.22523713 -0.8133488 ]
 [-0.2188668  -0.29429702 -0.83695718 -0.51244138 -0.72919691 -0.32470714
  -0.76106692 -0.37987903 -0.22523713 -0.8133488 ]
 [-0.2188668  -0.29429702 -0.83

Créer une fonction, appelée l2, qui calcule la distance euclidienne entre deux points donnés en entrée. Ces points sont de taille $1\times d$. 

In [18]:
def l2(point1, point2):
    return np.sqrt(np.sum((point1 - point2)**2))

Créer une fonction, appelée l1, qui calcule la distance de Manhattan  entre deux points donnés en entrée. Ces points sont de taille $1\times d$. 

In [ ]:
def l1(point1, point2):
    """Calcule la distance de Manhattan entre deux points"""
    return np.sum(np.abs(point1 - point2))

Créer une fonction, appelée frobenius_norm, qui reçoit un tableau ndarray de taille $n\times d$ et renvoie le résultat de l'opération suivante:

\begin{equation*}
\sqrt{ \sum_{i=1}^m \sum_{j=1}^d |a_{ij}|^2 }  
\end{equation*}

In [19]:
def frobenius_norm(array):
    """Calcule la norme de Frobenius d'un tableau ndarray"""
    return np.sqrt(np.sum(array**2))

## Implémentation de k-means

Dans cette partie, nous allons implémenter l'agorithme de k-means.

Créer une fonction f0 qui choisit k (entier naturel positif) points au hasard à partir d'un jeu de données donné en entrée. L'entier k est aussi donné en entrée de la fonction f0.

In [20]:
def f0(data, k):
    """Choisit k points au hasard à partir d'un jeu de données"""
    indices = np.random.choice(data.shape[0], k, replace=False)
    return data[indices]

Créer une fonction f1 qui calcule la distance entre chaque point d'un jeu de données donné en entrée et les k centroides donnés en entrée. La mesure de distance est aussi renseignée (par exemple euclidienne, manhattan...).
En sortie, une liste de clusters est attendue. Chaque cluster correspond à la liste d'indices de ses points.

Note: La distance euclidienne est le choix par défaut si l'utilisateur ne renseigne aucune mesure de distance. 

In [22]:
def f1(data, centroids, distance='euclidean'):
    """Calcule la distance entre chaque point et les k centroides donnés en entrée"""
    
    # Déterminer la fonction de distance à utiliser
    if distance == 'euclidean':
        dist_func = lambda x, y: np.sqrt(np.sum((x - y)**2))
    elif distance == 'manhattan':
        dist_func = lambda x, y: np.sum(np.abs(x - y))
    else:
        raise ValueError('La mesure de distance spécifiée est invalide')
    
    # Initialiser les clusters
    clusters = [[] for _ in range(len(centroids))]
    
    # Assigner chaque point au cluster le plus proche
    for i, point in enumerate(data):
        dist_to_centroids = [dist_func(point, centroid) for centroid in centroids]
        closest_centroid_index = np.argmin(dist_to_centroids)
        clusters[closest_centroid_index].append(i)
    
    return clusters

Créer la fonction f2 qui calcule les centroïdes des clusters nouvellement constitués.

In [23]:
def f2(data, clusters):
    """Calcule les centroïdes des clusters nouvellement constitués"""
    
    centroids = []
    
    for cluster in clusters:
        if len(cluster) == 0:
            # Si un cluster est vide, nous ne pouvons pas calculer son centroïde
            # Dans ce cas, nous initialisons le centroïde à un vecteur nul
            centroid = np.zeros(data.shape[1])
        else:
            # Nous calculons le centroïde en prenant la moyenne des points du cluster
            centroid = np.mean(data[cluster], axis=0)
        centroids.append(centroid)
    
    return np.array(centroids)


Créer la fonction f3 qui vérifie s'il y a convergence de k-means. La fonction f3 doit proposer trois moyens de vérification de la convergence:
- les centroïdes de l'itération précédente sont les mêmes que ceux de l'iteration actuelle;
- la norme de Frobenius de la différence des valeurs des centroides de deux itérations consécutives ne dépasse pas un seuil donné en paramètre par l'utilisateur (par exemple 0.001)
- le seuil maximal d'itérations est dépassé (seuil renseigné par l'utilisateur). Ce choix est une option par défaut, la valeur par défaut est fixée à 30.

In [24]:
def f3(centroids_old, centroids_new, threshold_fro, max_iter):
    """Vérifie s'il y a convergence de k-means en utilisant trois critères différents"""
    
    # Vérification de la convergence basée sur les centroïdes
    if np.array_equal(centroids_old, centroids_new):
        return True
    
    # Vérification de la convergence basée sur la norme de Frobenius
    if np.linalg.norm(centroids_old - centroids_new) < threshold_fro:
        return True
    
    # Vérification du nombre maximal d'itérations
    if max_iter <= 0:
        return True
    
    return False

Créer la fonction, appelée run, qui exécute itérativement les trois fonctions f1, f2, f3 jusqu'à convergence. 
La fonction f0 est appelée une seule fois à la première itération.
Dans cette même fonction run, proposer la visualisation des centroides et les clusters associés. A chaque cluster on associe une couleur. 
La visualisation n'est lancée seulement si l'utilisateur le souhaite. 

In [ ]:
import matplotlib.pyplot as plt
from typing import List


def run(data: np.ndarray, k: int, distance='euclidean', threshold=0.001, max_iterations=30, show_plot=True):
    # Initialisation
    centroids = f0(data, k)
    clusters = [[] for _ in range(k)]
    previous_centroids = np.zeros_like(centroids)

    # Itérations
    for i in range(max_iterations):
        # Assigner chaque point à un cluster
        clusters = f1(data, centroids, distance)

        # Calculer les nouveaux centroïdes
        centroids = f2(data, clusters)

        # Vérifier la convergence
        if f3(previous_centroids, centroids, threshold):
            print(f"Convergence atteinte après {i+1} itérations")
            break

        # Mise à jour des centroïdes de l'itération précédente
        previous_centroids = centroids.copy()

    # Visualisation des clusters et des centroïdes
    if show_plot:
        colors = ['r', 'g', 'b', 'c', 'm', 'y', 'k']
        for i, cluster in enumerate(clusters):
            plt.scatter(data[cluster][:, 0], data[cluster][:, 1], c=colors[i % len(colors)])
        plt.scatter(centroids[:, 0], centroids[:, 1], marker='x', s=200, linewidths=3, c='k')
        plt.show()

    # Retourner les clusters et les centroides
    return clusters, centroids

# Application de k-means sur un jeu de données synthétique

Générer un jeu de données synthétique via la méthode make_blobs (https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_blobs.ht). Fixer le nombre de points (n_samples) à 2000 et le nombre de clusters (centers) à 4.

Appliquer k-means sur ce jeu de données avec $k=4$. Visualiser le résultat final.

Relancer k-means et visualiser les résultats de 10 premières itérations.

Relancer k-means en variant les différents choix de vérification de la convergence. Que constatez-vous?

Note: les centroides initiaux et la mesure de distance doivent être les mêmes pour chacun des choix.

Créer un autre jeu de données synthétique. Choisissez un nombre de clusters et un nombre de points que vous souhaitez. Puis lancer à nouveau k-means avec k égal au nombre de clusters choisi. 

Note: vous pourriez créer optionnellement  un jeu de données plus personnalisé en jouant sur les valeurs des paramètres centers, cluster_std et center_box.

## Application de k-means sur une image

Dans cette partie, nous allons effectuer une fragmentation de l'image "nature.jpg". Cela aboutira à plusieurs parties de forme variable représentant différents objects dans l'image.

Charger l'image nature.jpg avec la bibliothèque cv2. Puis afficher l'image.

Quelle est la taille de l'image? Stocker cette taille dans une variable appelée taille_originale.

Convertir l'image chargée à la taille $n\times 3$ avec $n$ le nombre de pixels et 3 le nombre de cannaux de couleurs. Puis afficher dans un graphe 3D l'image. 

Appliquer k-means sur l'image avec $k=3$. 

Note: si le temps d'exécution est relativement lent (dépassant 10 minutes), réduisez la taille de l'image avec la fonction resize proposée par la bibliothèque cv2 puis réexécuter les questions précédentes de cette partie.

Créer un tableau ndarray de taille $n\times 3$ contenant la valeur du centroide le plus proche de chaque point (pixel).

Convertir la taille de ce tableau à taille originale de l'image.  

Visualiser l'image originale et l'image obtenue via k-means. Qu'observez-vous?

Références:
- https://docs.anaconda.com/anaconda/install/windows/
- https://docs.python.org/3/library/random.html
- https://numpy.org/doc/stable/numpy-ref.pdf
- https://numpy.org/
- https://matplotlib.org/stable/tutorials/index.html
- https://docs.opencv.org/3.0-beta/modules/imgcodecs/doc/reading_and_writing_images.html 
- https://docs.opencv.org/3.0-beta/modules/imgproc/doc/geometric_transformations.html?highlight=resize#cv2.resize